### PR TITLE
KAT-300: Update to Ruby 3

### PR DESCRIPTION
**Pull request by faustus7**
This pull updates from Ruby 2.2 to 3.0.

### CODE REVIEW

**Comment by mkostick** [comment]
Is this repo even still used?  It's marked deprecated in the README.

**Comment by kwong-yw** [comment]
> Is this repo even still used? It's marked deprecated in the README.

According to a quick GitHub search it looks like it's still used in Backend and all-mail for some reason 🤔 

https://github.com/Yesware/Backend/blob/main/Gemfile.lock#L8-L12

https://github.com/Yesware/all-mail/blob/main/Gemfile.lock#L2-L5

Although I wonder if it's only brought in for `big-brother-client-rb`, in which case maybe we can drop it from those two apps without any other changes.

**Comment by faustus7** [comment]
> Is this repo even still used? It's marked deprecated in the README.

I was wondering the same, but I found the straggling usages of this repo as highlighted by Kenny.

**Comment by faustus7** [comment]
> > Is this repo even still used? It's marked deprecated in the README.
> 
> I was wondering the same, but I found the straggling usages of this repo as highlighted by Kenny.

I am also under the impression that we had moved away from wanting to use JSON-API for structuring our APIs.

**Comment by kwong-yw** [comment]
I did some more digging– as of v2.0.0 of big-brother-client-rb, we no longer use JSON API, so I've removed it in all-mail here: https://github.com/Yesware/all-mail/pull/507 ~and we should be able to do the same in Backend.~

Correction– in Backend, because we have `cantina-client`, it seems like we still need `json_api_client` here 😬 looking to see if we can update that old gem to drop the JSON API requirement though.

**Review by kwong-yw — COMMENTED** [review]
I took a closer look at cantina-client, the only other place we're using `json_api_client`, and unfortunately it's not as easy a swap as `big-brother-client-rb` was I think. For now, I'd be okay with bumping this to support Ruby 3 and look into ripping out JSON API around MessageIndexes later.

If we go ahead with this version bump though, we should update the version and changelog at the very least.

Alternatively, I think we'd want to switch cantina-client to `yeti_json_api_client` and update that gem to Ruby 3.

**Review by kwong-yw — APPROVED** [review]

**Comment by faustus7** [comment]
Thanks!

**Pull request merged**
